networks:
  kafka_red:
    external: true
services:
  db:
    image: mysql
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./inicializar.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - kafka_red
  mongodb:
    image: mongo:latest
    container_name: mi_mongodb_cont
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kafka_red
  obtener:
    build: 
      context: ../fuente/obtenerdatos
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - kafka_red
  apises:
    container_name: fuente_api
    build:
      context: ../fuente/mandardatos
    networks:
      - kafka_red
    depends_on:
      - obtener
      - mongodb
    ports:
      - "5001:5000"
  kafka:
    depends_on:
      - db
    build:
      context: miDockerfile
      dockerfile: Dockerfile
    networks:
      - kafka_red
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  myservice:
    depends_on:
      - kafka
      - db
      - apises
    build:
      context: ../obtenerdatos
      dockerfile: Dockerfile
    networks:
      - kafka_red
volumes:
  db_data:
  mongo_data:
