networks:
  kafka_red:
    external: true
services:
  db:
    image: mysql
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./indices.txt:/var/lib/mysql-files/indices.txt
      - ./inicializar.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - kafka_red
  kafka:
    depends_on:
      - db
    build:
      context: miDockerfile
      dockerfile: Dockerfile
    networks:
      - kafka_red
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  myservice:
    depends_on:
      - kafka
      - db
    build:
      context: ../obtenerdatos
      dockerfile: Dockerfile
    networks:
      - kafka_red
  mandardatos:
    depends_on:
      - kafka
      - db
    build:
      context: ../mandardatos
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    networks:
      - kafka_red
volumes:
  db_data:
  mongo_data:
